language: c


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libantlr3c-dev antlr3 libcunit1-dev 
  - git clone https://github.com/Gui13/belle-sip.git
  - cd belle-sip
  - ./autogen.sh
  - ./configure
  - make -j4
  - sudo make install
  - cd ..
  - ./autogen.sh


script:
  - ./configure
  - make -j4


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "cllwBfAxeKDPqKR+Psg64vRoOXGKP77Xoa+4wglyHifKcCmJlFuQFpJvsT7SJnr0tHFg/WsZpeOwP1cG0K/I1hLMa1SgoXpujaVITrg7oBFdeIN7AhvaUNTL5IFCbXuXUs1DIhKB3/kNCLzbBIOOrZ+VVLXbrQBsndZ6MT8XFUI="

addons:
  coverity_scan:
    project:
      name: "Gui13/linphone"
      description: "Your project description here"
    notification_email: guitreize@gmail.com
    build_command_prepend: ./configure
    build_command: make -j4
    branch_pattern: coverity_scan